routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('layout.app');
});

// Route::get('student', function() {
//     return view('student.index');
// });
Route::resource('piket', 'PlaceController');
Route::resource('student', 'StudentController');
Route::resource('group', 'GroupController');

app/Group.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Group extends Model
{
    protected $table = 'groups';
    
    protected $fillable = ['group'];


    public function student()
    {
        return $this->hasMany(Student::class); 
    }
}
 

app/Http/Controllers/GroupController.php
<?php
 
namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Group;
use App\Student;

class GroupController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {   
        $groups = Student::all();      
        return view('group.index', compact('groups'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $group = new Group();
        $group->group = $request->group;

        $group->save();

        return redirect('group')->with('Success', 'Group has been added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/group/index.blade.php
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="bootstrap-4.1.1/dist/css/bootstrap.min.css">
	<style>
		h5{
			text-align: center;
			padding: 10px;
		}
 
		table {
			text-align: center;
		}

		th {
			padding:10px;
			text-align: center;
		}

		.table {
			border : 1px solid #000;
		}
	</style>
    <title>Jadwal piket</title>
  </head>
  <body style="background-color: #ccc;">
    
  <div class="container" style="background-color: white">
		<div class="row" >
			<div class="container" style="margin:50px;">
			@if (\Session::has('success'))
				<div class="alert alert-success">
					<p>{{ \Session::get('success') }}</p>
				</div><br />
			@endif 
				<div class="col-6">
					<form  method="post" action="{{ route('group.store') }}">
						{{ csrf_field() }}
						<div class="index"  >
							<label >Group</label>
							<input type="text" name="group">
						</div>
						
						<div class="form-group">
							<input type="submit" style="background:blue" class="btn btn-primary" value="Save">
						</div>
					</form>
				</div>
			


				<div class="col-6">
					<h5>Nama</h5>
					
					<table class="table">
						<thead>
							<tr>
								<th>No</th>
								<th>Group</th>
								<th>Nama</th>
							</tr>
						</thead>
						<tbody>
                            @php ($no = 1) @endphp
                            @foreach($groups as $group)
							<tr>
								<td>{{ $no++ }}</td>
								<td>{{ $group->group->group }}</td>
								<td>{{ $group->name }}</td>
                            </tr>
                            @endforeach
						</tbody>
					</table>
					
				</div>
			</div>
		</div>
	</div>

    <script src="bootstrap-4.1.1/dist/js/bootstrap.min.js"></script>
  </body>
</html>